#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data in sorted order

awk '{ count[$1" "$9]++ } END { for (ipcode in count) print count[ipcode], ipcode }' /root/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/apache-access.log | sort -k1,1nr | head -n 10
