#!/usr/bin/env bash
# This script displays "Best School" 10 times, but says "Hi" on the 9th iteration using a while loop and if statement

count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
